;;;; types.lisp - Data types for development workflow
;;;;
;;;; Part of Feature 041: Development Workflow Establishment
;;;; Defines structures for source modules, dependency graphs, caching, and compilation

(in-package #:clysm/workflow)

;;; ============================================================
;;; T007: SourceModule - A source module to be compiled
;;; ============================================================

(defstruct source-module
  "A source module to be compiled."
  (path "" :type string)              ; Absolute file path
  (relative-path "" :type string)     ; Path relative to project root
  (package nil :type (or symbol null)) ; Package name from in-package
  (mtime 0 :type integer)             ; File modification timestamp (Unix epoch)
  (hash "" :type string)              ; Content hash (SHA-256 hex)
  (forms nil :type list)              ; Parsed S-expressions
  (form-count 0 :type integer)        ; Number of top-level forms
  (dependencies nil :type list)       ; List of required module paths
  (status :pending :type keyword))    ; :pending, :compiling, :compiled, :failed, :skipped

;;; ============================================================
;;; T008: CompilationError - Error with location info
;;; ============================================================

(defstruct compilation-error
  "Error during compilation with location info."
  (severity :error :type keyword)       ; :error or :warning
  (message "" :type string)             ; Human-readable message
  (path "" :type string)                ; Source file path
  (line 0 :type integer)                ; Line number (1-based, 0 if unknown)
  (column 0 :type integer)              ; Column number (1-based, 0 if unknown)
  (form nil :type t)                    ; The form that caused the error
  (operator nil :type symbol)           ; The operator that failed (for grouping)
  (suggestion nil :type (or string null))) ; Optional fix suggestion

;;; ============================================================
;;; T009: CompilationResult - Outcome of compiling a module
;;; ============================================================

(defstruct compilation-result
  "Result of compiling a single module."
  (module nil :type (or source-module null)) ; The module that was compiled
  (success-p nil :type boolean)         ; Overall success
  (wasm-bytes nil :type t)              ; Generated Wasm bytes (or nil)
  (byte-count 0 :type integer)          ; Size of generated bytes
  (form-count 0 :type integer)          ; Total forms in module
  (forms-compiled 0 :type integer)      ; Forms successfully compiled
  (forms-failed 0 :type integer)        ; Forms that failed
  (forms-skipped 0 :type integer)       ; Forms skipped (e.g., metadata)
  (errors nil :type list)               ; List of compilation-error
  (warnings nil :type list)             ; List of compilation-error (with :warning severity)
  (compile-time-ms 0 :type integer))    ; Time to compile

;;; ============================================================
;;; T010: CompilationOptions - User-specified settings
;;; ============================================================

(defstruct compilation-options
  "Options controlling compilation behavior."
  (output "" :type string)              ; Output file path
  (verbose nil :type boolean)           ; Verbose output
  (force nil :type boolean)             ; Force full recompilation
  (continue-on-error t :type boolean)   ; Continue after errors
  (cache-path "" :type string)          ; Cache directory path
  (progress-callback nil :type t))      ; Function for progress updates

;;; ============================================================
;;; T011: ProgressInfo - Current compilation progress
;;; ============================================================

(defstruct progress-info
  "Current compilation progress."
  (phase :init :type keyword)           ; :init, :reading, :analyzing, :compiling, :linking, :done
  (total-modules 0 :type integer)       ; Total modules to process
  (current-module 0 :type integer)      ; Index of current module
  (current-path "" :type string)        ; Path of current module
  (percentage 0.0 :type single-float)   ; Overall progress 0.0-100.0
  (message "" :type string))            ; Status message

;;; ============================================================
;;; T012: CompilationSession - State for a compilation run
;;; ============================================================

(defstruct compilation-session
  "State of an active compilation session."
  (start-time 0 :type integer)          ; Session start (Unix epoch ms)
  (project-root "" :type string)        ; Project root path
  (output-path "" :type string)         ; Target output file
  (input-patterns nil :type list)       ; Original glob patterns
  (modules nil :type list)              ; All modules to consider
  (dirty-modules nil :type list)        ; Modules requiring recompilation
  (results nil :type list)              ; List of compilation-result
  (errors nil :type list)               ; Aggregated errors
  (progress nil :type (or progress-info null)) ; Current progress state
  (options nil :type (or compilation-options null))) ; Session options

;;; ============================================================
;;; Additional types for dependency graph and caching
;;; ============================================================

(defstruct dependency-graph
  "Module dependency graph for compilation ordering."
  (modules nil :type list)              ; List of source-module
  (path-index nil :type (or hash-table null)) ; path -> source-module
  (order nil :type list)                ; Topological order (path list)
  (dependents nil :type (or hash-table null)) ; path -> list of dependent paths
  (dependencies nil :type (or hash-table null))) ; path -> list of dependency paths

(defstruct cached-module
  "Cached compilation result for a single module."
  (path "" :type string)                ; Relative path
  (mtime 0 :type integer)               ; Modification time when compiled
  (hash "" :type string)                ; Content hash when compiled
  (compiled-size 0 :type integer)       ; Size of compiled Wasm bytes
  (compiled-bytes nil :type t)          ; Wasm bytes (or nil if not cached)
  (compile-time-ms 0 :type integer)     ; Compilation duration
  (form-results nil :type list))        ; Per-form success/failure

(defstruct compilation-cache
  "Persistent cache for incremental compilation."
  (version 1 :type integer)             ; Cache format version
  (timestamp "" :type string)           ; Last save time (ISO-8601)
  (project-root "" :type string)        ; Project root path
  (modules nil :type (or hash-table null)) ; path -> cached-module
  (dependency-graph nil :type t))       ; Serialized graph snapshot
