;;;; gc-types.lisp - WasmGC type definitions
;;;; Defines the type system for Clysm's Lisp objects in WasmGC

(in-package #:clysm/compiler/codegen/gc-types)

;;; ============================================================
;;; Type Indices for Standard Clysm Types
;;; ============================================================

(defconstant +type-nil+ 0 "Type index for NIL singleton")
(defconstant +type-unbound+ 1 "Type index for UNBOUND sentinel")
(defconstant +type-cons+ 2 "Type index for cons cells")
(defconstant +type-symbol+ 3 "Type index for symbols")
(defconstant +type-string+ 4 "Type index for strings")
(defconstant +type-closure+ 5 "Type index for closures")
(defconstant +type-instance+ 6 "Type index for CLOS instances")
(defconstant +type-standard-class+ 7 "Type index for standard classes")
;; Function types for closure arity dispatch
;; These indices must match the actual type section layout in compiler.lisp
(defconstant +type-func-0+ 8 "Type index for 0-arg function type")
(defconstant +type-func-1+ 9 "Type index for 1-arg function type")
(defconstant +type-func-2+ 10 "Type index for 2-arg function type")
(defconstant +type-func-3+ 11 "Type index for 3-arg function type")
(defconstant +type-func-n+ 12 "Type index for N-arg function type")
;; Dynamic binding support - comes after function types
;; NOTE: binding-frame is generated by generate-type-definitions after func types
(defconstant +type-binding-frame+ 13 "Type index for binding frame")

;;; ============================================================
;;; Numeric Tower Type Indices (T001)
;;; ============================================================
;; These types extend the numeric tower beyond fixnum (i31ref)
(defconstant +type-bignum+ 14 "Type index for arbitrary-precision integers")
(defconstant +type-ratio+ 15 "Type index for exact rational numbers")
(defconstant +type-float+ 16 "Type index for IEEE 754 double-precision floats")
(defconstant +type-complex+ 17 "Type index for complex numbers")
(defconstant +type-limb-array+ 18 "Type index for bignum limb array")

;;; ============================================================
;;; Stream Type Index (015-ffi-stream-io)
;;; ============================================================
(defconstant +type-stream+ 19 "Type index for stream objects")

;;; ============================================================
;;; Multiple Values Type Index (025-multiple-values)
;;; ============================================================
(defconstant +type-mv-array+ 20 "Type index for multiple values buffer array")

;;; ============================================================
;;; CLOS Foundation Type Indices (026-clos-foundation)
;;; ============================================================
(defconstant +type-slot-vector+ 21 "Type index for CLOS slot storage array")
(defconstant +type-keyword-array+ 22 "Type index for CLOS initarg keyword array")
(defconstant +type-closure-array+ 23 "Type index for CLOS initform closure array")

;;; ============================================================
;;; FFI Type Indices (027-complete-ffi)
;;; ============================================================
;; Note: Reuse +type-slot-vector+ (21) for anyref arrays in FFI calls
;; since it has the same structure: (array (mut anyref))
(defconstant +type-anyref-array+ 21 "Type index for anyref array (aliased from slot-vector)")

;;; ============================================================
;;; WasmGC Type Structures
;;; ============================================================

(defstruct (gc-type (:constructor nil))
  "Base structure for WasmGC types"
  (index nil :type (or null fixnum)))

(defstruct (wasm-struct-type (:include gc-type)
                             (:constructor make-wasm-struct-type))
  "WasmGC struct type definition"
  (name nil :type symbol)
  (fields nil :type list)
  (super nil :type (or null wasm-struct-type)))

(defstruct (wasm-array-type (:include gc-type)
                            (:constructor make-wasm-array-type))
  "WasmGC array type definition"
  (name nil :type symbol)
  (element-type nil :type keyword)
  (mutable t :type boolean))

(defstruct (wasm-func-type (:include gc-type)
                           (:constructor make-wasm-func-type))
  "WasmGC function type definition"
  (name nil :type symbol)
  (params nil :type list)    ; list of type keywords
  (results nil :type list))  ; list of type keywords

(defstruct (wasm-field)
  "WasmGC struct field definition"
  (name nil :type symbol)
  (type nil :type keyword)  ; :i32, :i64, :anyref, :i31ref, etc.
  (mutable t :type boolean))

;;; ============================================================
;;; Type Environment
;;; ============================================================

(defstruct (type-environment (:constructor %make-type-environment))
  "Environment tracking all defined types"
  (types (make-hash-table) :type hash-table)
  (next-index 0 :type fixnum))

(defun make-type-environment ()
  "Create a new type environment with standard types pre-registered"
  (let ((env (%make-type-environment)))
    ;; Register standard types
    (register-type env :nil)
    (register-type env :unbound)
    (register-type env :cons)
    (register-type env :symbol)
    (register-type env :string)
    (register-type env :closure)
    env))

(defun register-type (env type-key)
  "Register a type and return its index"
  (let ((types (type-environment-types env)))
    (or (gethash type-key types)
        (let ((idx (type-environment-next-index env)))
          (setf (gethash type-key types) idx)
          (incf (type-environment-next-index env))
          idx))))

(defun get-type-index (env type-key)
  "Get the index for a registered type"
  (gethash type-key (type-environment-types env)))

;;; ============================================================
;;; Fixnum Representation
;;; ============================================================

(defun fixnum-representation ()
  "Return the Wasm representation for fixnums"
  :i31ref)

;;; ============================================================
;;; Type Constructors (T033-T037)
;;; ============================================================

(defun make-nil-type ()
  "Create NIL singleton type (T033)
   NIL is represented as a struct with a single i32 tag field
   to distinguish it from other null references."
  (make-wasm-struct-type
   :name '$nil
   :index +type-nil+
   :fields (list (make-wasm-field :name 'tag :type :i32 :mutable nil))))

(defun make-unbound-type ()
  "Create UNBOUND sentinel type (T034)
   Used to detect unbound variables at runtime."
  (make-wasm-struct-type
   :name '$unbound
   :index +type-unbound+
   :fields (list (make-wasm-field :name 'tag :type :i32 :mutable nil))))

(defun make-cons-type ()
  "Create CONS cell type (T035)
   Cons cells have car and cdr fields, both anyref."
  (make-wasm-struct-type
   :name '$cons
   :index +type-cons+
   :fields (list (make-wasm-field :name 'car :type :anyref :mutable t)
                 (make-wasm-field :name 'cdr :type :anyref :mutable t))))

(defun make-symbol-type ()
  "Create symbol type (T036)
   Symbols have name, value, and function slots."
  (make-wasm-struct-type
   :name '$symbol
   :index +type-symbol+
   :fields (list (make-wasm-field :name 'name :type :anyref :mutable nil)    ; string ref
                 (make-wasm-field :name 'value :type :anyref :mutable t)     ; value cell
                 (make-wasm-field :name 'function :type :anyref :mutable t)  ; function cell
                 (make-wasm-field :name 'plist :type :anyref :mutable t))))  ; property list

(defun make-string-type ()
  "Create string type (T037)
   Strings are arrays of i8 (UTF-8 bytes).
   Mutable to support make-string and string modification operations."
  (make-wasm-array-type
   :name '$string
   :index +type-string+
   :element-type :i8
   :mutable t))

;;; ============================================================
;;; Function Type Constructors (for closure arity dispatch)
;;; ============================================================

(defun make-func-type-0 ()
  "Create function type for 0-arg functions (T075)
   (func (param (ref $closure)) (result anyref))"
  (make-wasm-func-type
   :name '$func_0
   :index +type-func-0+
   :params '(:closure-ref)      ; (ref $closure)
   :results '(:anyref)))

(defun make-func-type-1 ()
  "Create function type for 1-arg functions (T075)
   (func (param (ref $closure) anyref) (result anyref))"
  (make-wasm-func-type
   :name '$func_1
   :index +type-func-1+
   :params '(:closure-ref :anyref)
   :results '(:anyref)))

(defun make-func-type-2 ()
  "Create function type for 2-arg functions (T075)
   (func (param (ref $closure) anyref anyref) (result anyref))"
  (make-wasm-func-type
   :name '$func_2
   :index +type-func-2+
   :params '(:closure-ref :anyref :anyref)
   :results '(:anyref)))

(defun make-func-type-3 ()
  "Create function type for 3-arg functions (T075)
   (func (param (ref $closure) anyref anyref anyref) (result anyref))"
  (make-wasm-func-type
   :name '$func_3
   :index +type-func-3+
   :params '(:closure-ref :anyref :anyref :anyref)
   :results '(:anyref)))

(defun make-func-type-n ()
  "Create function type for N-arg functions (T075)
   (func (param (ref $closure) (ref $list)) (result anyref))"
  (make-wasm-func-type
   :name '$func_N
   :index +type-func-n+
   :params '(:closure-ref :list-ref)  ; (ref $closure) (ref $list)
   :results '(:anyref)))

(defun make-closure-type ()
  "Create closure type (T076)
   Closures have arity-specific code pointers and environment.
   $code_0: 0-arg entry point (nullable funcref)
   $code_1: 1-arg entry point (nullable funcref)
   $code_2: 2-arg entry point (nullable funcref)
   $code_N: N-arg entry point (nullable funcref)
   $env: Captured environment (mutable anyref)"
  (make-wasm-struct-type
   :name '$closure
   :index +type-closure+
   :fields (list (make-wasm-field :name 'code_0 :type :funcref :mutable nil)
                 (make-wasm-field :name 'code_1 :type :funcref :mutable nil)
                 (make-wasm-field :name 'code_2 :type :funcref :mutable nil)
                 (make-wasm-field :name 'code_n :type :funcref :mutable nil)
                 (make-wasm-field :name 'env :type :anyref :mutable t))))

;;; ============================================================
;;; Dynamic Binding Support (T003-T004)
;;; ============================================================

(defun make-binding-frame-type ()
  "Create binding frame type (T003)
   Used for tracking dynamic bindings during execution.
   $symbol: The bound symbol (ref $symbol)
   $old_value: Previous value before binding (anyref)
   $prev: Link to previous frame (ref null $binding_frame)"
  (make-wasm-struct-type
   :name '$binding_frame
   :index +type-binding-frame+
   :fields (list (make-wasm-field :name 'symbol :type :symbol-ref :mutable nil)
                 (make-wasm-field :name 'old_value :type :anyref :mutable nil)
                 (make-wasm-field :name 'prev :type :binding-frame-ref :mutable nil))))

(defun emit-binding-stack-global ()
  "Generate WAT for the global binding stack (T004).
   Returns a string of WAT code for the $binding_stack global variable.
   (global $binding_stack (mut (ref null $binding_frame)) (ref.null $binding_frame))"
  (format nil "(global $binding_stack (mut (ref null ~D)) (ref.null ~D))"
          +type-binding-frame+ +type-binding-frame+))

;;; ============================================================
;;; Numeric Tower Type Constructors (T002-T006)
;;; ============================================================

(defun make-limb-array-type ()
  "Create limb array type for bignum representation (T002).
   An array of mutable i32 values representing bignum limbs in little-endian order.
   (type $limb_array (array (mut i32)))"
  (make-wasm-array-type
   :name '$limb_array
   :index +type-limb-array+
   :element-type :i32
   :mutable t))

(defun make-bignum-type ()
  "Create bignum type for arbitrary-precision integers (T003).
   Structure:
     $sign: i32 (0 = non-negative, 1 = negative)
     $limbs: ref $limb_array (array of 32-bit limbs, little-endian)
   (type $bignum (struct
     (field $sign i32)
     (field $limbs (ref $limb_array))))"
  (make-wasm-struct-type
   :name '$bignum
   :index +type-bignum+
   :fields (list (make-wasm-field :name 'sign :type :i32 :mutable nil)
                 (make-wasm-field :name 'limbs :type :limb-array-ref :mutable nil))))

(defun make-ratio-type ()
  "Create ratio type for exact rational numbers (T004).
   Structure:
     $numerator: anyref (fixnum or bignum, carries sign)
     $denominator: anyref (positive fixnum or bignum, never zero)
   Invariants:
     - GCD(|numerator|, denominator) = 1 (always reduced)
     - denominator > 0
   (type $ratio (struct
     (field $numerator anyref)
     (field $denominator anyref)))"
  (make-wasm-struct-type
   :name '$ratio
   :index +type-ratio+
   :fields (list (make-wasm-field :name 'numerator :type :anyref :mutable nil)
                 (make-wasm-field :name 'denominator :type :anyref :mutable nil))))

(defun make-float-type ()
  "Create float type for IEEE 754 double-precision numbers (T005).
   Structure:
     $value: f64 (IEEE 754 binary64)
   Note: Both single-float and double-float use f64 internally.
   Boxing is required for anyref compatibility.
   (type $float (struct (field $value f64)))"
  (make-wasm-struct-type
   :name '$float
   :index +type-float+
   :fields (list (make-wasm-field :name 'value :type :f64 :mutable nil))))

(defun make-complex-type ()
  "Create complex type for complex numbers (T006).
   Structure:
     $real: anyref (fixnum, bignum, ratio, or float)
     $imag: anyref (fixnum, bignum, ratio, or float)
   Invariants:
     - If imag is exact 0 and real is rational, simplify to real
     - #C(5.0 0.0) stays complex (float zero is not exact zero)
   (type $complex (struct
     (field $real anyref)
     (field $imag anyref)))"
  (make-wasm-struct-type
   :name '$complex
   :index +type-complex+
   :fields (list (make-wasm-field :name 'real :type :anyref :mutable nil)
                 (make-wasm-field :name 'imag :type :anyref :mutable nil))))

;;; ============================================================
;;; Multiple Values Type Constructor (025-multiple-values)
;;; ============================================================

(defun make-mv-array-type ()
  "Create multiple values buffer array type (025-multiple-values).
   An array of mutable anyref for storing secondary values.
   (type $mv_array (array (mut anyref)))"
  (make-wasm-array-type
   :name '$mv_array
   :index +type-mv-array+
   :element-type :anyref
   :mutable t))

;;; ============================================================
;;; Stream Type Constructor (015-ffi-stream-io, T006)
;;; ============================================================

(defun make-stream-type ()
  "Create stream type for I/O operations (015-ffi-stream-io).
   Structure:
     $fd: i32 (host file descriptor: 0=stdin, 1=stdout, 2=stderr)
     $direction: i32 (0=input, 1=output, 2=bidirectional)
   (type $stream (struct
     (field $fd i32)
     (field $direction i32)))"
  (make-wasm-struct-type
   :name '$stream
   :index +type-stream+
   :fields (list (make-wasm-field :name 'fd :type :i32 :mutable nil)
                 (make-wasm-field :name 'direction :type :i32 :mutable nil))))

;;; ============================================================
;;; CLOS Foundation Type Constructors (026-clos-foundation)
;;; ============================================================

(defun make-instance-type ()
  "Create CLOS instance type (026-clos-foundation).
   Structure:
     $class: (ref $standard-class) - reference to class metadata
     $slots: (ref $slot-vector) - slot values array
   (type $instance (struct
     (field $class (ref $standard-class))
     (field $slots (ref $slot-vector))))"
  (make-wasm-struct-type
   :name '$instance
   :index +type-instance+
   :fields (list (make-wasm-field :name 'class :type :standard-class-ref :mutable nil)
                 (make-wasm-field :name 'slots :type :slot-vector-ref :mutable nil))))

(defun make-standard-class-type ()
  "Create CLOS standard-class type (026-clos-foundation).
   Structure:
     $name: (ref $symbol) - class name symbol
     $superclass: (ref null $standard-class) - nullable parent class
     $slot_count: i32 - total slots including inherited
     $initargs: (ref $keyword-array) - initarg keywords per slot
     $initforms: (ref $closure-array) - initform closures per slot
     $class_id: i32 - unique dispatch index
   (type $standard-class (struct
     (field $name (ref $symbol))
     (field $superclass (ref null $standard-class))
     (field $slot_count i32)
     (field $initargs (ref $keyword-array))
     (field $initforms (ref $closure-array))
     (field $class_id i32)))"
  (make-wasm-struct-type
   :name '$standard-class
   :index +type-standard-class+
   :fields (list (make-wasm-field :name 'name :type :symbol-ref :mutable nil)
                 (make-wasm-field :name 'superclass :type :standard-class-ref-null :mutable nil)
                 (make-wasm-field :name 'slot_count :type :i32 :mutable nil)
                 (make-wasm-field :name 'initargs :type :keyword-array-ref :mutable nil)
                 (make-wasm-field :name 'initforms :type :closure-array-ref :mutable nil)
                 (make-wasm-field :name 'class_id :type :i32 :mutable nil))))

(defun make-slot-vector-type ()
  "Create CLOS slot vector type (026-clos-foundation).
   An array of mutable anyref values for slot storage.
   (type $slot-vector (array (mut anyref)))"
  (make-wasm-array-type
   :name '$slot-vector
   :index +type-slot-vector+
   :element-type :anyref
   :mutable t))

(defun make-keyword-array-type ()
  "Create CLOS keyword array type (026-clos-foundation).
   An array of symbol references for initarg keywords.
   (type $keyword-array (array (ref $symbol)))"
  (make-wasm-array-type
   :name '$keyword-array
   :index +type-keyword-array+
   :element-type :symbol-ref
   :mutable nil))

(defun make-closure-array-type ()
  "Create CLOS closure array type (026-clos-foundation).
   An array of nullable closure references for initform expressions.
   (type $closure-array (array (ref null $closure)))"
  (make-wasm-array-type
   :name '$closure-array
   :index +type-closure-array+
   :element-type :closure-ref-null
   :mutable nil))

;;; ============================================================
;;; Exception Tags (T008)
;;; ============================================================

(defconstant +tag-division-by-zero+ 0 "Tag index for division-by-zero exception")

(defun emit-division-by-zero-tag ()
  "Generate WAT for the division-by-zero exception tag (T008).
   Returns a string of WAT code for the exception tag.
   (tag $division-by-zero (type $empty))
   Note: Exception tags in WasmGC use exception handling proposal.
   The tag has no parameters (empty type) - signaling just indicates the error."
  "(tag $division-by-zero)")

;;; ============================================================
;;; Struct Fields Accessor
;;; ============================================================

(defun struct-fields (struct-type)
  "Get the fields of a struct type"
  (wasm-struct-type-fields struct-type))

;;; ============================================================
;;; Type Section Generation (T038)
;;; ============================================================

(defun generate-type-definitions ()
  "Generate all WasmGC type definitions for the Type Section (T007).
   Returns a list of type definitions in order of their indices.
   Type layout:
     0-5: GC struct types (nil, unbound, cons, symbol, string, closure)
     6-7: CLOS types (instance, standard-class)
     8-12: Function types (func_0, func_1, func_2, func_3, func_n)
     13: Binding frame (for dynamic bindings)
     14: Bignum (arbitrary-precision integer)
     15: Ratio (exact rational number)
     16: Float (IEEE 754 double-precision)
     17: Complex (complex number)
     18: Limb array (for bignum limbs)
     19: Stream (I/O operations)
     20: Multiple values buffer array
     21-23: CLOS array types (slot-vector, keyword-array, closure-array)"
  (list (make-nil-type)             ; type 0
        (make-unbound-type)         ; type 1
        (make-cons-type)            ; type 2
        (make-symbol-type)          ; type 3
        (make-string-type)          ; type 4
        (make-closure-type)         ; type 5
        (make-instance-type)        ; type 6: CLOS instance (026-clos-foundation)
        (make-standard-class-type)  ; type 7: CLOS class metadata (026-clos-foundation)
        (make-func-type-0)          ; type 8
        (make-func-type-1)          ; type 9
        (make-func-type-2)          ; type 10
        (make-func-type-3)          ; type 11
        (make-func-type-n)          ; type 12
        (make-binding-frame-type)   ; type 13: binding frame for dynamic bindings
        (make-bignum-type)          ; type 14: arbitrary-precision integer
        (make-ratio-type)           ; type 15: exact rational number
        (make-float-type)           ; type 16: IEEE 754 double-precision
        (make-complex-type)         ; type 17: complex number
        (make-limb-array-type)      ; type 18: bignum limb array
        (make-stream-type)          ; type 19: stream object (015-ffi-stream-io)
        (make-mv-array-type)        ; type 20: multiple values buffer (025-multiple-values)
        (make-slot-vector-type)     ; type 21: CLOS slot storage (026-clos-foundation)
        (make-keyword-array-type)   ; type 22: CLOS initarg keywords (026-clos-foundation)
        (make-closure-array-type))) ; type 23: CLOS initform closures (026-clos-foundation)

(defun emit-type-to-binary (type stream)
  "Emit a type definition to the binary stream.
   Uses WasmGC encoding for struct, array, and function types."
  (etypecase type
    (null
     ;; Skip nil placeholders
     nil)
    (wasm-struct-type
     (emit-struct-type type stream))
    (wasm-array-type
     (emit-array-type type stream))
    (wasm-func-type
     (emit-func-type type stream))))

(defun emit-func-type (func-type stream)
  "Emit a WasmGC function type definition"
  ;; func type encoding: 0x60, param_count, params..., result_count, results...
  (write-byte #x60 stream)  ; func type
  (let ((params (wasm-func-type-params func-type))
        (results (wasm-func-type-results func-type)))
    (clysm/backend/leb128:encode-unsigned-leb128-to-stream (length params) stream)
    (dolist (param params)
      (emit-value-type-extended param stream))
    (clysm/backend/leb128:encode-unsigned-leb128-to-stream (length results) stream)
    (dolist (result results)
      (emit-value-type-extended result stream))))

(defun emit-value-type-extended (type-keyword stream)
  "Emit a Wasm value type byte (extended for closure types)"
  (ecase type-keyword
    (:i32 (write-byte #x7F stream))
    (:i64 (write-byte #x7E stream))
    (:f32 (write-byte #x7D stream))
    (:f64 (write-byte #x7C stream))
    (:anyref (write-byte #x6F stream))
    (:funcref (write-byte #x70 stream))
    (:i31ref (write-byte #x6C stream))
    (:eqref (write-byte #x6D stream))
    ;; Reference types with type index
    (:closure-ref
     ;; (ref null $closure) - nullable reference to closure type
     (write-byte #x63 stream)  ; ref null
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-closure+ stream))
    (:list-ref
     ;; (ref null $cons) - for argument list
     (write-byte #x63 stream)  ; ref null
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-cons+ stream))
    ;; Dynamic binding support (T003)
    (:symbol-ref
     ;; (ref $symbol) - non-null reference to symbol
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-symbol+ stream))
    (:binding-frame-ref
     ;; (ref null $binding_frame) - nullable reference to binding frame
     (write-byte #x63 stream)  ; ref null
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-binding-frame+ stream))
    ;; Numeric tower type references (T002-T006)
    (:limb-array-ref
     ;; (ref $limb_array) - non-null reference to limb array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-limb-array+ stream))
    (:bignum-ref
     ;; (ref $bignum) - non-null reference to bignum
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-bignum+ stream))
    (:ratio-ref
     ;; (ref $ratio) - non-null reference to ratio
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-ratio+ stream))
    (:float-ref
     ;; (ref $float) - non-null reference to float
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-float+ stream))
    (:complex-ref
     ;; (ref $complex) - non-null reference to complex
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-complex+ stream))
    ;; Stream type reference (015-ffi-stream-io, T008)
    (:stream-ref
     ;; (ref $stream) - non-null reference to stream
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-stream+ stream))
    ;; Multiple values buffer reference (025-multiple-values)
    (:mv-array-ref
     ;; (ref $mv_array) - non-null reference to mv buffer array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-mv-array+ stream))
    ;; CLOS Foundation type references (026-clos-foundation)
    (:instance-ref
     ;; (ref $instance) - non-null reference to CLOS instance
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-instance+ stream))
    (:standard-class-ref
     ;; (ref $standard-class) - non-null reference to class
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-standard-class+ stream))
    (:standard-class-ref-null
     ;; (ref null $standard-class) - nullable reference to class (for superclass)
     (write-byte #x63 stream)  ; ref null
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-standard-class+ stream))
    (:slot-vector-ref
     ;; (ref $slot-vector) - non-null reference to slot array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-slot-vector+ stream))
    (:keyword-array-ref
     ;; (ref $keyword-array) - non-null reference to keyword array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-keyword-array+ stream))
    (:closure-array-ref
     ;; (ref $closure-array) - non-null reference to closure array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-closure-array+ stream))
    (:closure-ref-null
     ;; (ref null $closure) - nullable reference to closure (for initforms)
     (write-byte #x63 stream)  ; ref null
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-closure+ stream))))

(defun emit-struct-type (struct-type stream)
  "Emit a WasmGC struct type definition"
  ;; struct type encoding: 0x5F (sub), 0x5C (no super), field_count, fields...
  ;; Simplified: 0x5F (struct), field_count, fields...
  (write-byte #x5F stream)  ; struct type
  (let ((fields (wasm-struct-type-fields struct-type)))
    (clysm/backend/leb128:encode-unsigned-leb128-to-stream (length fields) stream)
    (dolist (field fields)
      (emit-field-type field stream))))

(defun emit-array-type (array-type stream)
  "Emit a WasmGC array type definition"
  ;; array type encoding: 0x5E, element_type, mutability
  (write-byte #x5E stream)  ; array type
  (emit-value-type (wasm-array-type-element-type array-type) stream)
  (write-byte (if (wasm-array-type-mutable array-type) 1 0) stream))

(defun emit-field-type (field stream)
  "Emit a struct field type"
  (emit-value-type (wasm-field-type field) stream)
  (write-byte (if (wasm-field-mutable field) 1 0) stream))

(defun emit-value-type (type-keyword stream)
  "Emit a Wasm value type byte"
  (case type-keyword
    ;; Simple types - just emit the byte
    ((:i32 :i64 :f32 :f64 :i8 :i16 :anyref :funcref :i31ref :eqref :structref)
     (write-byte
      (ecase type-keyword
        (:i32 #x7F)
        (:i64 #x7E)
        (:f32 #x7D)
        (:f64 #x7C)
        (:i8 #x78)      ; i8 for array elements
        (:i16 #x77)     ; i16 for array elements
        (:anyref #x6F)  ; externref in core, anyref in GC
        (:funcref #x70)
        (:i31ref #x6C)  ; i31ref (WasmGC)
        (:eqref #x6D)   ; eqref (WasmGC)
        (:structref #x6B)) ; structref (WasmGC)
      stream))
    ;; Reference types with type index (T003 dynamic binding support)
    (:symbol-ref
     ;; (ref $symbol) - non-null reference to symbol
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-symbol+ stream))
    (:binding-frame-ref
     ;; (ref null $binding_frame) - nullable reference to binding frame
     (write-byte #x63 stream)  ; ref null
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-binding-frame+ stream))
    ;; Numeric tower type references (T002-T006)
    (:limb-array-ref
     ;; (ref $limb_array) - non-null reference to limb array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-limb-array+ stream))
    (:bignum-ref
     ;; (ref $bignum) - non-null reference to bignum
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-bignum+ stream))
    (:ratio-ref
     ;; (ref $ratio) - non-null reference to ratio
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-ratio+ stream))
    (:float-ref
     ;; (ref $float) - non-null reference to float
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-float+ stream))
    (:complex-ref
     ;; (ref $complex) - non-null reference to complex
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-complex+ stream))
    ;; Stream type reference (015-ffi-stream-io)
    (:stream-ref
     ;; (ref $stream) - non-null reference to stream
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-stream+ stream))
    ;; Multiple values buffer reference (025-multiple-values)
    (:mv-array-ref
     ;; (ref $mv_array) - non-null reference to mv buffer array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-mv-array+ stream))
    ;; CLOS Foundation type references (026-clos-foundation)
    (:instance-ref
     ;; (ref $instance) - non-null reference to CLOS instance
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-instance+ stream))
    (:standard-class-ref
     ;; (ref $standard-class) - non-null reference to class
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-standard-class+ stream))
    (:standard-class-ref-null
     ;; (ref null $standard-class) - nullable reference to class (for superclass)
     (write-byte #x63 stream)  ; ref null
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-standard-class+ stream))
    (:slot-vector-ref
     ;; (ref $slot-vector) - non-null reference to slot array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-slot-vector+ stream))
    (:keyword-array-ref
     ;; (ref $keyword-array) - non-null reference to keyword array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-keyword-array+ stream))
    (:closure-array-ref
     ;; (ref $closure-array) - non-null reference to closure array
     (write-byte #x64 stream)  ; ref (non-null)
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-closure-array+ stream))
    (:closure-ref-null
     ;; (ref null $closure) - nullable reference to closure (for initforms)
     (write-byte #x63 stream)  ; ref null
     (clysm/backend/leb128:encode-signed-leb128-to-stream +type-closure+ stream))
    (t (error "Unknown value type: ~A" type-keyword))))
