;;;; repl/loader.lisp - JavaScript Module Loader Generator
;;;;
;;;; Generates JavaScript code for loading Clysm Wasm modules
;;;; in browsers and Node.js environments.

(in-package #:clysm)

;;; ============================================================
;;; JavaScript Template
;;; ============================================================

(defparameter *js-loader-template*
  "// Clysm Wasm Module Loader
// Generated by Clysm Compiler

(function(global) {
  'use strict';

  // Clysm runtime imports for Wasm modules
  const imports = {
    env: {
      // Memory management (stub for GC-based modules)
      memory: new WebAssembly.Memory({ initial: 1 }),

      // Console output
      print_i32: function(x) {
        console.log(x);
      },

      print_string: function(ptr, len) {
        // Would need memory access for actual string printing
        console.log('[string at', ptr, 'len', len, ']');
      },

      // Error handling
      error: function(msg_ptr) {
        throw new Error('Clysm runtime error');
      }
    }
  };

  // Decode i31ref to JavaScript number
  function decodeI31(ref) {
    // i31ref is a 31-bit signed integer
    // In GC-enabled Wasm, this is unboxed
    return ref;
  }

  // Decode anyref result to JavaScript value
  function decodeResult(result) {
    if (result === null || result === undefined) {
      return null;  // NIL
    }
    if (typeof result === 'number') {
      return result;  // Fixnum
    }
    if (typeof result === 'object') {
      // Could be cons, symbol, closure, etc.
      // For now, return as-is
      return result;
    }
    return result;
  }

  // Load a Clysm Wasm module
  async function loadModule(source) {
    let wasmModule;

    if (typeof source === 'string') {
      // URL or path
      if (typeof fetch !== 'undefined') {
        // Browser
        const response = await fetch(source);
        const buffer = await response.arrayBuffer();
        wasmModule = await WebAssembly.instantiate(buffer, imports);
      } else {
        // Node.js
        const fs = require('fs');
        const buffer = fs.readFileSync(source);
        wasmModule = await WebAssembly.instantiate(buffer, imports);
      }
    } else if (source instanceof ArrayBuffer) {
      wasmModule = await WebAssembly.instantiate(source, imports);
    } else if (source instanceof Uint8Array) {
      wasmModule = await WebAssembly.instantiate(source.buffer, imports);
    } else {
      throw new Error('Invalid module source');
    }

    return wasmModule.instance;
  }

  // Clysm runtime object
  const Clysm = {
    // Load a module from URL, path, or bytes
    load: loadModule,

    // Evaluate a pre-compiled module
    async eval(wasmBytes) {
      const instance = await loadModule(wasmBytes);
      if (instance.exports._start) {
        return decodeResult(instance.exports._start());
      } else if (instance.exports.main) {
        return decodeResult(instance.exports.main());
      } else {
        throw new Error('No entry point found');
      }
    },

    // Call an exported function
    async call(wasmBytes, funcName, ...args) {
      const instance = await loadModule(wasmBytes);
      const func = instance.exports[funcName];
      if (!func) {
        throw new Error('Function not found: ' + funcName);
      }
      return decodeResult(func(...args));
    },

    // Decode a Wasm result value
    decode: decodeResult,

    // Version info
    version: '0.1.0'
  };

  // Export for different environments
  if (typeof module !== 'undefined' && module.exports) {
    // Node.js
    module.exports = Clysm;
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define(function() { return Clysm; });
  } else {
    // Browser global
    global.Clysm = Clysm;
  }

})(typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : this);
"
  "JavaScript template for Clysm module loader.")

;;; ============================================================
;;; Loader Generation
;;; ============================================================

(defun generate-js-loader (&optional pathname)
  "Generate the JavaScript loader file.
If PATHNAME is provided, write to file. Otherwise return string."
  (if pathname
      (with-open-file (stream pathname
                              :direction :output
                              :if-exists :supersede)
        (write-string *js-loader-template* stream)
        pathname)
      *js-loader-template*))

(defun generate-html-test-page (wasm-path &optional html-path)
  "Generate an HTML test page for a Wasm module.
WASM-PATH is the path to the Wasm file.
HTML-PATH is the output HTML file path."
  (let ((html (format nil "<!DOCTYPE html>
<html>
<head>
  <meta charset=\"utf-8\">
  <title>Clysm Test</title>
  <script>
~A
  </script>
</head>
<body>
  <h1>Clysm Test Page</h1>
  <pre id=\"output\">Loading...</pre>
  <script>
    (async function() {
      const output = document.getElementById('output');
      try {
        const result = await Clysm.eval('~A');
        output.textContent = 'Result: ' + JSON.stringify(result);
      } catch (e) {
        output.textContent = 'Error: ' + e.message;
      }
    })();
  </script>
</body>
</html>"
                      *js-loader-template*
                      wasm-path)))
    (if html-path
        (with-open-file (stream html-path
                                :direction :output
                                :if-exists :supersede)
          (write-string html stream)
          html-path)
        html)))

;;; ============================================================
;;; Module Bundling
;;; ============================================================

(defun bundle-wasm-module (wasm-bytes &key (format :esm))
  "Bundle Wasm bytes as a JavaScript module.
FORMAT can be :esm (ES Module) or :cjs (CommonJS)."
  (let ((bytes-str (format nil "[~{~D~^,~}]" wasm-bytes)))
    (ecase format
      (:esm
       (format nil "// Clysm bundled module (ES Module)
const wasmBytes = new Uint8Array(~A);
export default wasmBytes;
export { wasmBytes };
" bytes-str))
      (:cjs
       (format nil "// Clysm bundled module (CommonJS)
const wasmBytes = new Uint8Array(~A);
module.exports = wasmBytes;
module.exports.wasmBytes = wasmBytes;
" bytes-str)))))

(defun bundle-to-file (wasm-bytes pathname &key (format :esm))
  "Bundle Wasm bytes to a JavaScript file."
  (let ((content (bundle-wasm-module wasm-bytes :format format)))
    (with-open-file (stream pathname
                            :direction :output
                            :if-exists :supersede)
      (write-string content stream))
    pathname))
