;;;; instructions.lisp - WebAssembly instruction opcodes

(in-package #:clysm/wasm)

;;; Control Instructions
(defconstant +op-unreachable+ #x00)
(defconstant +op-nop+ #x01)
(defconstant +op-block+ #x02)
(defconstant +op-loop+ #x03)
(defconstant +op-if+ #x04)
(defconstant +op-else+ #x05)
;; 0x06-0x0a reserved
(defconstant +op-end+ #x0b)
(defconstant +op-br+ #x0c)
(defconstant +op-br-if+ #x0d)
(defconstant +op-br-table+ #x0e)
(defconstant +op-return+ #x0f)
(defconstant +op-call+ #x10)
(defconstant +op-call-indirect+ #x11)

;;; Tail Call Extension
(defconstant +op-return-call+ #x12)
(defconstant +op-return-call-indirect+ #x13)

;;; Parametric Instructions
(defconstant +op-drop+ #x1a)
(defconstant +op-select+ #x1b)
(defconstant +op-select-typed+ #x1c)

;;; Variable Instructions
(defconstant +op-local-get+ #x20)
(defconstant +op-local-set+ #x21)
(defconstant +op-local-tee+ #x22)
(defconstant +op-global-get+ #x23)
(defconstant +op-global-set+ #x24)

;;; Table Instructions
(defconstant +op-table-get+ #x25)
(defconstant +op-table-set+ #x26)

;;; Memory Instructions
(defconstant +op-i32-load+ #x28)
(defconstant +op-i64-load+ #x29)
(defconstant +op-f32-load+ #x2a)
(defconstant +op-f64-load+ #x2b)
(defconstant +op-i32-load8-s+ #x2c)
(defconstant +op-i32-load8-u+ #x2d)
(defconstant +op-i32-load16-s+ #x2e)
(defconstant +op-i32-load16-u+ #x2f)
(defconstant +op-i64-load8-s+ #x30)
(defconstant +op-i64-load8-u+ #x31)
(defconstant +op-i64-load16-s+ #x32)
(defconstant +op-i64-load16-u+ #x33)
(defconstant +op-i64-load32-s+ #x34)
(defconstant +op-i64-load32-u+ #x35)
(defconstant +op-i32-store+ #x36)
(defconstant +op-i64-store+ #x37)
(defconstant +op-f32-store+ #x38)
(defconstant +op-f64-store+ #x39)
(defconstant +op-i32-store8+ #x3a)
(defconstant +op-i32-store16+ #x3b)
(defconstant +op-i64-store8+ #x3c)
(defconstant +op-i64-store16+ #x3d)
(defconstant +op-i64-store32+ #x3e)
(defconstant +op-memory-size+ #x3f)
(defconstant +op-memory-grow+ #x40)

;;; Numeric Instructions - Constants
(defconstant +op-i32-const+ #x41)
(defconstant +op-i64-const+ #x42)
(defconstant +op-f32-const+ #x43)
(defconstant +op-f64-const+ #x44)

;;; Numeric Instructions - i32 Comparison
(defconstant +op-i32-eqz+ #x45)
(defconstant +op-i32-eq+ #x46)
(defconstant +op-i32-ne+ #x47)
(defconstant +op-i32-lt-s+ #x48)
(defconstant +op-i32-lt-u+ #x49)
(defconstant +op-i32-gt-s+ #x4a)
(defconstant +op-i32-gt-u+ #x4b)
(defconstant +op-i32-le-s+ #x4c)
(defconstant +op-i32-le-u+ #x4d)
(defconstant +op-i32-ge-s+ #x4e)
(defconstant +op-i32-ge-u+ #x4f)

;;; Numeric Instructions - i64 Comparison
(defconstant +op-i64-eqz+ #x50)
(defconstant +op-i64-eq+ #x51)
(defconstant +op-i64-ne+ #x52)
(defconstant +op-i64-lt-s+ #x53)
(defconstant +op-i64-lt-u+ #x54)
(defconstant +op-i64-gt-s+ #x55)
(defconstant +op-i64-gt-u+ #x56)
(defconstant +op-i64-le-s+ #x57)
(defconstant +op-i64-le-u+ #x58)
(defconstant +op-i64-ge-s+ #x59)
(defconstant +op-i64-ge-u+ #x5a)

;;; Numeric Instructions - f32 Comparison
(defconstant +op-f32-eq+ #x5b)
(defconstant +op-f32-ne+ #x5c)
(defconstant +op-f32-lt+ #x5d)
(defconstant +op-f32-gt+ #x5e)
(defconstant +op-f32-le+ #x5f)
(defconstant +op-f32-ge+ #x60)

;;; Numeric Instructions - f64 Comparison
(defconstant +op-f64-eq+ #x61)
(defconstant +op-f64-ne+ #x62)
(defconstant +op-f64-lt+ #x63)
(defconstant +op-f64-gt+ #x64)
(defconstant +op-f64-le+ #x65)
(defconstant +op-f64-ge+ #x66)

;;; Numeric Instructions - i32 Arithmetic
(defconstant +op-i32-clz+ #x67)
(defconstant +op-i32-ctz+ #x68)
(defconstant +op-i32-popcnt+ #x69)
(defconstant +op-i32-add+ #x6a)
(defconstant +op-i32-sub+ #x6b)
(defconstant +op-i32-mul+ #x6c)
(defconstant +op-i32-div-s+ #x6d)
(defconstant +op-i32-div-u+ #x6e)
(defconstant +op-i32-rem-s+ #x6f)
(defconstant +op-i32-rem-u+ #x70)
(defconstant +op-i32-and+ #x71)
(defconstant +op-i32-or+ #x72)
(defconstant +op-i32-xor+ #x73)
(defconstant +op-i32-shl+ #x74)
(defconstant +op-i32-shr-s+ #x75)
(defconstant +op-i32-shr-u+ #x76)
(defconstant +op-i32-rotl+ #x77)
(defconstant +op-i32-rotr+ #x78)

;;; Numeric Instructions - i64 Arithmetic
(defconstant +op-i64-clz+ #x79)
(defconstant +op-i64-ctz+ #x7a)
(defconstant +op-i64-popcnt+ #x7b)
(defconstant +op-i64-add+ #x7c)
(defconstant +op-i64-sub+ #x7d)
(defconstant +op-i64-mul+ #x7e)
(defconstant +op-i64-div-s+ #x7f)
(defconstant +op-i64-div-u+ #x80)
(defconstant +op-i64-rem-s+ #x81)
(defconstant +op-i64-rem-u+ #x82)
(defconstant +op-i64-and+ #x83)
(defconstant +op-i64-or+ #x84)
(defconstant +op-i64-xor+ #x85)
(defconstant +op-i64-shl+ #x86)
(defconstant +op-i64-shr-s+ #x87)
(defconstant +op-i64-shr-u+ #x88)
(defconstant +op-i64-rotl+ #x89)
(defconstant +op-i64-rotr+ #x8a)

;;; Numeric Instructions - f32 Arithmetic
(defconstant +op-f32-abs+ #x8b)
(defconstant +op-f32-neg+ #x8c)
(defconstant +op-f32-ceil+ #x8d)
(defconstant +op-f32-floor+ #x8e)
(defconstant +op-f32-trunc+ #x8f)
(defconstant +op-f32-nearest+ #x90)
(defconstant +op-f32-sqrt+ #x91)
(defconstant +op-f32-add+ #x92)
(defconstant +op-f32-sub+ #x93)
(defconstant +op-f32-mul+ #x94)
(defconstant +op-f32-div+ #x95)
(defconstant +op-f32-min+ #x96)
(defconstant +op-f32-max+ #x97)
(defconstant +op-f32-copysign+ #x98)

;;; Numeric Instructions - f64 Arithmetic
(defconstant +op-f64-abs+ #x99)
(defconstant +op-f64-neg+ #x9a)
(defconstant +op-f64-ceil+ #x9b)
(defconstant +op-f64-floor+ #x9c)
(defconstant +op-f64-trunc+ #x9d)
(defconstant +op-f64-nearest+ #x9e)
(defconstant +op-f64-sqrt+ #x9f)
(defconstant +op-f64-add+ #xa0)
(defconstant +op-f64-sub+ #xa1)
(defconstant +op-f64-mul+ #xa2)
(defconstant +op-f64-div+ #xa3)
(defconstant +op-f64-min+ #xa4)
(defconstant +op-f64-max+ #xa5)
(defconstant +op-f64-copysign+ #xa6)

;;; Numeric Instructions - Conversions
(defconstant +op-i32-wrap-i64+ #xa7)
(defconstant +op-i32-trunc-f32-s+ #xa8)
(defconstant +op-i32-trunc-f32-u+ #xa9)
(defconstant +op-i32-trunc-f64-s+ #xaa)
(defconstant +op-i32-trunc-f64-u+ #xab)
(defconstant +op-i64-extend-i32-s+ #xac)
(defconstant +op-i64-extend-i32-u+ #xad)
(defconstant +op-i64-trunc-f32-s+ #xae)
(defconstant +op-i64-trunc-f32-u+ #xaf)
(defconstant +op-i64-trunc-f64-s+ #xb0)
(defconstant +op-i64-trunc-f64-u+ #xb1)
(defconstant +op-f32-convert-i32-s+ #xb2)
(defconstant +op-f32-convert-i32-u+ #xb3)
(defconstant +op-f32-convert-i64-s+ #xb4)
(defconstant +op-f32-convert-i64-u+ #xb5)
(defconstant +op-f32-demote-f64+ #xb6)
(defconstant +op-f64-convert-i32-s+ #xb7)
(defconstant +op-f64-convert-i32-u+ #xb8)
(defconstant +op-f64-convert-i64-s+ #xb9)
(defconstant +op-f64-convert-i64-u+ #xba)
(defconstant +op-f64-promote-f32+ #xbb)

;;; Reinterpret
(defconstant +op-i32-reinterpret-f32+ #xbc)
(defconstant +op-i64-reinterpret-f64+ #xbd)
(defconstant +op-f32-reinterpret-i32+ #xbe)
(defconstant +op-f64-reinterpret-i64+ #xbf)

;;; Sign extension
(defconstant +op-i32-extend8-s+ #xc0)
(defconstant +op-i32-extend16-s+ #xc1)
(defconstant +op-i64-extend8-s+ #xc2)
(defconstant +op-i64-extend16-s+ #xc3)
(defconstant +op-i64-extend32-s+ #xc4)

;;; Reference Instructions
(defconstant +op-ref-null+ #xd0)
(defconstant +op-ref-is-null+ #xd1)
(defconstant +op-ref-func+ #xd2)
(defconstant +op-ref-eq+ #xd3)
(defconstant +op-ref-as-non-null+ #xd4)

;;; GC Prefix (0xfb)
(defconstant +gc-prefix+ #xfb)

;;; GC Instructions (after 0xfb prefix)
(defconstant +op-struct-new+ 0)
(defconstant +op-struct-new-default+ 1)
(defconstant +op-struct-get+ 2)
(defconstant +op-struct-get-s+ 3)
(defconstant +op-struct-get-u+ 4)
(defconstant +op-struct-set+ 5)
(defconstant +op-array-new+ 6)
(defconstant +op-array-new-default+ 7)
(defconstant +op-array-new-fixed+ 8)
(defconstant +op-array-new-data+ 9)
(defconstant +op-array-new-elem+ 10)
(defconstant +op-array-get+ 11)
(defconstant +op-array-get-s+ 12)
(defconstant +op-array-get-u+ 13)
(defconstant +op-array-set+ 14)
(defconstant +op-array-len+ 15)
(defconstant +op-array-fill+ 16)
(defconstant +op-array-copy+ 17)
(defconstant +op-array-init-data+ 18)
(defconstant +op-array-init-elem+ 19)
(defconstant +op-ref-test+ 20)
(defconstant +op-ref-test-null+ 21)
(defconstant +op-ref-cast+ 22)
(defconstant +op-ref-cast-null+ 23)
(defconstant +op-br-on-cast+ 24)
(defconstant +op-br-on-cast-fail+ 25)
(defconstant +op-any-convert-extern+ 26)
(defconstant +op-extern-convert-any+ 27)
(defconstant +op-ref-i31+ 28)
(defconstant +op-i31-get-s+ 29)
(defconstant +op-i31-get-u+ 30)

;;; Instruction encoding helpers

(defun encode-instruction (buffer opcode &rest args)
  "Encode an instruction with its opcode and arguments."
  (buffer-write-byte buffer opcode)
  (dolist (arg args)
    (etypecase arg
      ((unsigned-byte 8)
       (buffer-write-byte buffer arg))
      (integer
       (buffer-write-sleb128 buffer arg))
      (list
       (buffer-write-bytes buffer arg)))))

(defun encode-gc-instruction (buffer gc-opcode &rest args)
  "Encode a GC instruction (prefixed with 0xfb)."
  (buffer-write-byte buffer +gc-prefix+)
  (buffer-write-uleb128 buffer gc-opcode)
  (dolist (arg args)
    (etypecase arg
      ((unsigned-byte 8)
       (buffer-write-byte buffer arg))
      (integer
       (buffer-write-uleb128 buffer arg))
      (list
       (buffer-write-bytes buffer arg)))))
