;;; blessed-subset.lisp - Self-Compilable Common Lisp Subset for Clysm
;;;
;;; Generated: 2025-12-27
;;; Version: 1.0.0
;;;
;;; This file documents which CL features are verified to work in
;;; Clysm's self-compilation process.

(in-package :clysm-validation)

(defparameter *blessed-special-forms*
  '(BLOCK CATCH
     FLET
     GO
     IF
     LABELS
     LAMBDA
     LET
     LET*
     MULTIPLE-VALUE-CALL
     MULTIPLE-VALUE-PROG1
     QUOTE
     RETURN-FROM
     SETQ
     TAGBODY
     THROW
     UNWIND-PROTECT)
  "Special forms verified for self-compilation.")

(defparameter *blessed-macros*
  '(AND CASE COND DECF DEFCLASS DEFCONSTANT DEFINE-CONDITION DEFMACRO DEFMETHOD
        DEFPACKAGE DEFPARAMETER DEFSTRUCT DEFUN DEFVAR DESTRUCTURING-BIND DO
        DOLIST ECASE ETYPECASE INCF LOOP MULTIPLE-VALUE-BIND
        MULTIPLE-VALUE-LIST NOT NTH-VALUE OR OTHERWISE POP
        PRINT-UNREADABLE-OBJECT PROG1 PROGN PUSH RETURN SETF TYPECASE UNLESS
        VALUES VALUES-LIST WHEN WITH-OPEN-FILE WITH-OUTPUT-TO-STRING
        WITH-SIMPLE-RESTART)
  "Macros verified for self-compilation.")

(defparameter *blessed-functions*
  '(* *ERROR-OUTPUT* *STANDARD-INPUT* *STANDARD-OUTPUT* + - / /= 1+ 1- < <= = >
      >= ABORT ABS ALPHANUMERICP APPEND APPLY AREF ASH ASSOC ATOM BOUNDP CAAR
      CADDR CADR CAR CDAR CDDR CDR CEILING CERROR CHAR CHAR= CHARACTERP
      CHECK-TYPE CLASS-NAME CLRHASH COERCE COMPILE COMPLEXP
      COMPUTE-APPLICABLE-METHODS COMPUTE-RESTARTS CONCATENATE CONJUGATE CONSP
      CONTINUE COPY-LIST COUNT-IF-NOT DENOMINATOR DIGIT-CHAR-P EQ EQL EQUAL
      EVENP EVERY EXPORT EXPT FIND FIND-IF FIND-PACKAGE FIND-RESTART
      FIND-SYMBOL FIRST FLOATP FLOOR FORMAT FOURTH FUNCALL FUNCTIONP GCD GENSYM
      GETF GETHASH HANDLER-BIND HANDLER-CASE HASH-TABLE-COUNT HASH-TABLE-P
      IMAGPART IMPORT IN-PACKAGE INTEGERP INTERN INVOKE-DEBUGGER INVOKE-RESTART
      INVOKE-RESTART-INTERACTIVELY KEYWORDP LCM LENGTH LISTP LOGAND LOGBITP
      LOGIOR MACROEXPAND MACROEXPAND-1 MAKE-ARRAY MAKE-CONDITION
      MAKE-HASH-TABLE MAKE-INSTANCE MAKE-STRING MAPCAR MAPHASH MEMBER MINUSP
      MOD MUFFLE-WARNING NREVERSE NTH NTHCDR NULL NUMBERP NUMERATOR ODDP
      PARSE-INTEGER PLUSP POSITION PRIN1 PRINC RATIONALP READ-CHAR
      READ-FROM-STRING REALP REALPART REDUCE REM REMHASH REMOVE REMOVE-IF
      REMOVE-IF-NOT REST RESTART-BIND RESTART-CASE REVERSE ROUND SECOND SIGNAL
      SIMPLE-CONDITION-FORMAT-ARGUMENTS SIMPLE-CONDITION-FORMAT-CONTROL SQRT
      STABLE-SORT STORE-VALUE STRING-DOWNCASE STRING-EQUAL STRING-UPCASE
      STRING= STRINGP SUBSEQ SYMBOL-NAME SYMBOL-VALUE SYMBOLP TERPRI THIRD
      TRUNCATE TYPE-OF TYPEP USE-VALUE VECTOR-PUSH-EXTEND WARN WRITE-BYTE
      WRITE-SEQUENCE ZEROP)
  "Functions verified for self-compilation.")

(defparameter *blessed-types*
  '(BOOLEAN BYTE CELL-ERROR CELL-ERROR-NAME CHARACTER CLASS COMPLEX CONDITION
    CONS CONTROL-ERROR DOUBLE-FLOAT END-OF-FILE ERROR FILE-ERROR FIXNUM FLOAT
    FUNCTION GENERIC-FUNCTION HASH-TABLE INTEGER KEYWORD LIST METHOD
    METHOD-COMBINATION PACKAGE PARSE-ERROR PATHNAME PROGRAM-ERROR RATIO RESTART
    SERIOUS-CONDITION SIMPLE-ARRAY SIMPLE-CONDITION SIMPLE-ERROR SIMPLE-VECTOR
    SIMPLE-WARNING SINGLE-FLOAT STANDARD-CLASS STREAM STREAM-ERROR STRING
    SYMBOL T TYPE-ERROR TYPE-ERROR-DATUM TYPE-ERROR-EXPECTED-TYPE
    UNBOUND-VARIABLE UNDEFINED-FUNCTION UNSIGNED-BYTE VECTOR WARNING)
  "Type specifiers verified for self-compilation.")

(defparameter *partial-support-notes*
  '(
    (DECLARE . "Declaration forms parsed but some may not affect codegen")
    (FORMAT . "Supports ~A ~S ~D ~B ~O ~X ~R ~C ~% ~& ~~ ~* ~? ~{ ~} ~[ ~] ~( ~)")
    (IGNORABLE . "Declaration forms parsed but some may not affect codegen")
    (IGNORE . "Declaration forms parsed but some may not affect codegen")
    (LOOP . "Only :for :collect :do :return :while :until :initially :finally supported")
    (TYPE . "Declaration forms parsed but some may not affect codegen"))
  "Notes for features with partial support.")
