;;;; package.lisp - Test package for ANSI test harness unit tests

(defpackage #:clysm/tests/unit/ansi-test
  (:use #:cl #:rove #:clysm/ansi-test)
  ;; Import struct predicates (auto-generated by defstruct but not exported)
  (:import-from #:clysm/ansi-test
                #:test-case-p
                #:test-result-p
                #:category-result-p
                #:report-summary-p
                #:coverage-report-p
                #:skip-registry-p
                #:baseline-comparison-p)
  (:documentation "Unit tests for the ANSI Common Lisp test harness."))
